name: .NET Core

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Download tix-factory/nuget nuget.zip
      uses: tix-factory/release-manager@v1
      with:
        github_token: ${{ secrets.github_token }}
        mode: downloadReleaseAsset
        filePath: ./build/tix-factory-nuget.zip
        assetName: nuget.zip
        tag: latest
        repo: nuget
        owner: tix-factory
    - name: unzip tix-factory-nuget.zip
      run: |
        unzip tix-factory-nuget.zip
        cp -r tix-factory-nuget ./../../../LocalNuGetRepo
      shell: bash
      working-directory: ./build
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Setup NuGet.exe
      uses: NuGet/setup-nuget@v1.0.2
    - name: Build Number Generator
      uses: einaregilsson/build-number@v2
      with:
        token: ${{ secrets.github_token }}
    - name: Build with dotnet
      run: bash build.sh
      shell: bash
      working-directory: ./build
    - name: Zip NuGet packages
      run: |
        cp -r ./../LocalNuGetRepo nuget
        zip -r nuget.zip nuget
        dir
      shell: bash
      working-directory: ./build
    - name: Create Release
      uses: tix-factory/release-manager@v1
      with:
        github_token: ${{ secrets.github_token }}
        mode: uploadReleaseAsset
        filePath: ./build/nuget.zip
        assetName: nuget.zip
        tag: ${{ format('release-number-{0}', env.BUILD_NUMBER) }}
    - name: Publish NuGet packages to github
      run: |
           nuget sources Add -Name "GPR" -Source https://nuget.pkg.github.com/roblox-plus/index.json -UserName roblox-plus -Password ${{ secrets.github_token }}
           nuget push ./LocalNuGetRepo/**/*.nupkg -Source "GPR" -NoSymbols
